version: '3.7'

services:
  api:
    image: docker-class:0.0.1
    depends_on:
      - elastic
    environment:
      - DB_HOST=elastic
      - DB_PORT=9200
      - SLEEP=1
      - TRIES=10
    volumes:
      - .:/home/docker-volume
    # command: "tail -f /dev/null"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - TZ=America/Sao_Paulo
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - node.name=Dockerized_elastic
    # ports:
    #   - 9200:9200
